#!/usr/bin/env python3
"""Correcta grading runner.

Mock mode is deterministic and file-based, designed to prove the pipeline.
OpenCode mode is intentionally conservative: it falls back to mock unless implemented/configured.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def score_to_letter(score: float) -> tuple[str, float]:
    scale = [
        ("A", 93, 4.0),
        ("A-", 90, 3.7),
        ("B+", 87, 3.3),
        ("B", 83, 3.0),
        ("B-", 80, 2.7),
        ("C+", 77, 2.3),
        ("C", 73, 2.0),
        ("C-", 70, 1.7),
        ("D", 60, 1.0),
        ("F", 0, 0.0),
    ]
    for letter, minimum, gpa in scale:
        if score >= minimum:
            return letter, gpa
    return "F", 0.0


def count_attempt_files(attempt_dir: Path) -> int:
    if not attempt_dir.exists():
        return 0
    return sum(1 for p in attempt_dir.rglob("*") if p.is_file() and not p.name.startswith("."))


def mock_grade(assignment: dict[str, Any], data: dict[str, Any], attempt_id: str, attempt_dir: Path) -> dict[str, Any]:
    rubric = assignment.get("rubric", [])
    file_count = count_attempt_files(attempt_dir)

    # Deterministic but slightly varied score.
    base = 82 + (len(assignment.get("assignmentId", "")) % 8)
    if file_count > 0:
        base += min(5, file_count)
    final_score = max(0, min(100, base))

    letter, gpa = score_to_letter(final_score)

    rubric_breakdown = []
    total_points = sum(int(r.get("points", 0)) for r in rubric) or 100
    for item in rubric:
        max_points = int(item.get("points", 0))
        earned = round(max_points * final_score / 100)
        rubric_breakdown.append(
            {
                "criterion": item.get("criterion", "Criterion"),
                "maxPoints": max_points,
                "earnedPoints": earned,
                "reason": "Mock grader: awarded proportionally based on detected submission and assignment structure.",
            }
        )

    return {
        "assignmentId": assignment.get("assignmentId"),
        "attemptId": attempt_id,
        "scoreBeforeLatePenalty": final_score,
        "latePenalty": 0,
        "finalScore": final_score,
        "letterGrade": letter,
        "gpaValue": gpa,
        "gradedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "rubricBreakdown": rubric_breakdown,
        "missingRequiredFiles": [],
        "summaryFeedback": "Mock feedback: submission was detected and graded successfully.",
        "deepNotes": (
            "This is mock grading. The pipeline is working: Correcta detected the uploaded files, "
            "created an attempt, generated grade.json, feedback.md, and notes.md, then updated assignment data."
        ),
        "recommendedFixes": [
            "Replace mock grading with OpenCode/AI grading when ready.",
            "Make sure required files match the assignment requirements.",
        ],
    }


def grade_attempt(
    course_dir: Path,
    assignment_dir: Path,
    assignment: dict[str, Any],
    data: dict[str, Any],
    attempt_id: str,
    grader: str = "mock",
) -> dict[str, Any]:
    attempt_dir = assignment_dir / "submissions" / attempt_id
    output_dir = assignment_dir / "ai_output" / attempt_id
    output_dir.mkdir(parents=True, exist_ok=True)

    # OpenCode hook placeholder. Keep safe fallback for now.
    if grader == "opencode":
        grade = mock_grade(assignment, data, attempt_id, attempt_dir)
        grade["summaryFeedback"] = "OpenCode mode is not fully configured yet; mock fallback was used."
    else:
        grade = mock_grade(assignment, data, attempt_id, attempt_dir)

    write_json(output_dir / "grade.json", grade)

    feedback_md = f"""# Feedback — {assignment.get('title', assignment.get('assignmentId'))}

Score: {grade['finalScore']}/100  
Letter Grade: {grade['letterGrade']}

## Summary

{grade['summaryFeedback']}

## Recommended Fixes

""" + "\n".join(f"- {x}" for x in grade.get("recommendedFixes", [])) + "\n"

    notes_md = f"""# Deep Notes — {assignment.get('title', assignment.get('assignmentId'))}

{grade['deepNotes']}

## Pipeline Note

Generated by Correcta `{grader}` grading mode for `{attempt_id}`.
"""

    write_text(output_dir / "feedback.md", feedback_md)
    write_text(output_dir / "notes.md", notes_md)

    return grade
